// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf3I8CNNWlr91x__i_HLOs0Ey83jDmmOU',
    appId: '1:250991021124:web:ca365c1e196ac3d24e0011',
    messagingSenderId: '250991021124',
    projectId: 'lab14-e7f86',
    authDomain: 'lab14-e7f86.firebaseapp.com',
    storageBucket: 'lab14-e7f86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgxes40CzdTuXg4jukb-R7Ekm8qaggdA',
    appId: '1:250991021124:android:01489c196115c9e04e0011',
    messagingSenderId: '250991021124',
    projectId: 'lab14-e7f86',
    storageBucket: 'lab14-e7f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkDRzsQWduW_eKM1sG0ztc1jdVnDowCbs',
    appId: '1:250991021124:ios:f1bdcb9808006ae34e0011',
    messagingSenderId: '250991021124',
    projectId: 'lab14-e7f86',
    storageBucket: 'lab14-e7f86.appspot.com',
    iosClientId: '250991021124-f7v735dm7uqcsardmpspgv4l484jrpv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab14',
  );
}
