// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3wwxR2fdvX30VglQhEqof1xbOtMYI128',
    appId: '1:1062419656340:web:aa749c9ddfdcc0c2e88e81',
    messagingSenderId: '1062419656340',
    projectId: 'assignment-provider',
    authDomain: 'assignment-provider.firebaseapp.com',
    storageBucket: 'assignment-provider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtThMxB8MoMsDayCuXKxw0j3EGiAjy8A',
    appId: '1:1062419656340:android:c1635f770df381ffe88e81',
    messagingSenderId: '1062419656340',
    projectId: 'assignment-provider',
    storageBucket: 'assignment-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHOYSsJWAAVSHaeXX2zxn3X-ivykyZ_s',
    appId: '1:1062419656340:ios:05bd406d4cc2fd95e88e81',
    messagingSenderId: '1062419656340',
    projectId: 'assignment-provider',
    storageBucket: 'assignment-provider.appspot.com',
    iosClientId: '1062419656340-4likrhfkf0lbkb9i0i294s6k9krang5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
