// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72NOa_n3d7gbTfpBydyNNejBUphmFnR4',
    appId: '1:1063308930103:web:76bb729e8b4127a0d363b2',
    messagingSenderId: '1063308930103',
    projectId: 'lab-12-8d00f',
    authDomain: 'lab-12-8d00f.firebaseapp.com',
    storageBucket: 'lab-12-8d00f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_59S9SKZ3oijh3uYVps0uTCTK9BC4PXg',
    appId: '1:1063308930103:android:fd46280d5f6d62bbd363b2',
    messagingSenderId: '1063308930103',
    projectId: 'lab-12-8d00f',
    storageBucket: 'lab-12-8d00f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4xdCvF0BFL7-LfIRK6PxF_X-MaNbRC0',
    appId: '1:1063308930103:ios:0b10dccc28760e27d363b2',
    messagingSenderId: '1063308930103',
    projectId: 'lab-12-8d00f',
    storageBucket: 'lab-12-8d00f.appspot.com',
    iosClientId: '1063308930103-53q0jhrh6u4ver0v66rbe6r72qn0dpap.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
