// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNp2hgSISLZesKUGLUw25WBV25ENXfDA',
    appId: '1:803146770934:web:e836b8e72bc3d14cec3fd7',
    messagingSenderId: '803146770934',
    projectId: 'expense-tracker-c7b39',
    authDomain: 'expense-tracker-c7b39.firebaseapp.com',
    storageBucket: 'expense-tracker-c7b39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9XIp6tQUappSSQ45K7HCHc6RvzkUwj4',
    appId: '1:803146770934:android:f466c600d648a128ec3fd7',
    messagingSenderId: '803146770934',
    projectId: 'expense-tracker-c7b39',
    storageBucket: 'expense-tracker-c7b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBey5jsGkXmEXQ1mwMfGmiL8FG5PogF3Pw',
    appId: '1:803146770934:ios:db150b8030604e38ec3fd7',
    messagingSenderId: '803146770934',
    projectId: 'expense-tracker-c7b39',
    storageBucket: 'expense-tracker-c7b39.appspot.com',
    iosClientId: '803146770934-0l57ql8oeja8ks4betpvmqus00npkbsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
